/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihsganjlokclienttcp;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aldo
 */
public class FormHistoriReservasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormHistoriReservasi.class.getName());

    /**
     * Creates new form FormHistoriReservasi
     */
public FormHistoriReservasi() {
   initComponents();

    jTextFieldDariTanggal.setText("2026-06-01");
    jTextFieldSampaiTanggal.setText("2026-06-30");

    viewHistory();
    tampilDetailBarisPertama();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
public void viewHistory() {
   DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
    model.setRowCount(0);

    String dariTanggal = jTextFieldDariTanggal.getText();
    String sampaiTanggal = jTextFieldSampaiTanggal.getText();
    String status = jComboBoxStatusReservasi.getSelectedItem().toString();

    try {
        List<String> dataHistory = kirimKeServerTCP(
                "HISTORY|" + dariTanggal + "|" + sampaiTanggal + "|" + status
        );

        for (String data : dataHistory) {
            String[] row = data.split("\\|");

            model.addRow(new Object[]{
                row[0],
                row[1],
                row[2],
                row[3],
                row[4],
                row[5],
                row[6]
            });
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan history: " + ex.getMessage());
    }


}

public void viewDetailPesanan(int reservasiID) {
DefaultTableModel model = (DefaultTableModel) tblDetail.getModel();
    model.setRowCount(0);

    int total = 0;

    try {
        List<String> dataDetail = kirimKeServerTCP(
                "DETAIL_HISTORY|" + reservasiID
        );

        for (String data : dataDetail) {
            String[] row = data.split("\\|");

            int subtotal = Integer.parseInt(row[4]);
            total = total + subtotal;

            model.addRow(new Object[]{
                row[0],
                row[1],
                row[2],
                row[3],
                row[4],
                row[5]
            });
        }

        lblTotal.setText("Total Pesanan: Rp " + total);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan detail pesanan: " + ex.getMessage());
    }
}

public void clearDetail() {
    DefaultTableModel model = (DefaultTableModel) tblDetail.getModel();
    model.setRowCount(0);

    lblTotal.setText("Total Pesanan: Rp 0");
}

public void refreshHistory() {
    jTextFieldDariTanggal.setText("2026-06-01");
    jTextFieldSampaiTanggal.setText("2026-06-30");
    jComboBoxStatusReservasi.setSelectedItem("Semua");

    viewHistory();
    clearDetail();
}
public List<String> kirimKeServerTCP(String pesan) {
    List<String> hasil = new ArrayList<String>();

    try {
        Socket socket = new Socket("localhost", 6000);

        PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
        BufferedReader in = new BufferedReader(
                new InputStreamReader(socket.getInputStream())
        );

        out.println(pesan);

        String response = in.readLine();

        if (response != null && !response.equals("")) {
            String[] rows = response.split("#");

            for (String row : rows) {
                hasil.add(row);
            }
        }

        in.close();
        out.close();
        socket.close();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Gagal koneksi ke TCP Server: " + ex.getMessage());
    }

    return hasil;
}
public void tampilDetailBarisPertama() {
    if (tblHistory.getRowCount() > 0) {
        tblHistory.setRowSelectionInterval(0, 0);

        int reservasiID = Integer.parseInt(tblHistory.getValueAt(0, 0).toString());

        viewDetailPesanan(reservasiID);
    } else {
        clearDetail();
    }
}



    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        scrollDetail = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        jButtonRefrase = new javax.swing.JButton();
        jButtonCari = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jTextFieldDariTanggal = new javax.swing.JTextField();
        jTextFieldSampaiTanggal = new javax.swing.JTextField();
        scrollHistory = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jComboBoxStatusReservasi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblJudul.setText("HISTORY RESERVASI");

        scrollDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Pesanan"));

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Kategori", "Jumlah", "Harga", "SubTotal", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetail.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollDetail.setViewportView(tblDetail);

        jButtonRefrase.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRefrase.setText("Refresh");
        jButtonRefrase.addActionListener(this::jButtonRefraseActionPerformed);

        jButtonCari.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(this::jButtonCariActionPerformed);

        lblTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotal.setText("Total Pesanan: Rp 0");

        label1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        label1.setText(" Dari Tanggal :");

        label2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        label2.setText("Status Reservasi :");

        label3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        label3.setText("Sampai Tanggal :");

        jTextFieldDariTanggal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextFieldDariTanggal.addActionListener(this::jTextFieldDariTanggalActionPerformed);

        jTextFieldSampaiTanggal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        scrollHistory.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel History Reservasi Final"));

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Reservasi", "Customer", "Nomor Meja", "Tanggal", "Jumlah Tamu", "Status Reservasi", "Total Pesanan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHistoryMouseClicked(evt);
            }
        });
        scrollHistory.setViewportView(tblHistory);

        jComboBoxStatusReservasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxStatusReservasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Pending", "Confirmed", "Completed", "Cancelled" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(lblJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jComboBoxStatusReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jButtonCari)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRefrase))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSampaiTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblJudul)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSampaiTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxStatusReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCari)
                            .addComponent(jButtonRefrase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(scrollDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
       viewHistory();
    tampilDetailBarisPertama();
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jTextFieldDariTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDariTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDariTanggalActionPerformed

    private void tblHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHistoryMouseClicked
         int baris = tblHistory.getSelectedRow();

    if (baris >= 0) {
        int reservasiID = Integer.parseInt(tblHistory.getValueAt(baris, 0).toString());

        viewDetailPesanan(reservasiID);
    }//GEN-LAST:event_tblHistoryMouseClicked
    }
    private void jButtonRefraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefraseActionPerformed
        // TODO add your handling code here:
    jTextFieldDariTanggal.setText("2026-06-01");
    jTextFieldSampaiTanggal.setText("2026-06-30");
    jComboBoxStatusReservasi.setSelectedItem("Semua");

    viewHistory();
    tampilDetailBarisPertama();
    }//GEN-LAST:event_jButtonRefraseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormHistoriReservasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonRefrase;
    private javax.swing.JComboBox<String> jComboBoxStatusReservasi;
    private javax.swing.JTextField jTextFieldDariTanggal;
    private javax.swing.JTextField jTextFieldSampaiTanggal;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JScrollPane scrollDetail;
    private javax.swing.JScrollPane scrollHistory;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tblHistory;
    // End of variables declaration//GEN-END:variables
}
