/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihsganjlokclienttcp;

/**
 *
 * @author LENOVO
 */
public class FormReservasi extends javax.swing.JFrame implements Runnable {

    Thread t;
    java.net.Socket clientSocket;
    java.io.BufferedReader inFromServer;
    java.io.DataOutputStream sendToServer;
    private int userId;
    private String nama;
    private String hakAkses;

    private void hitungTotalHarga() {
        int totalSemua = 0;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelReservasiMenu.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            int subtotal = Integer.parseInt(model.getValueAt(i, 5).toString());
            totalSemua += subtotal;
        }

        lblTotalHarga.setText("Total: Rp. " + totalSemua);
    }

    private void loadMenuToComboBox() {
        cmbMenuMakanan.removeAllItems();
        cmbMenuMinuman.removeAllItems();

        try {
            com.ihsganjlok.services.MenuManagementWebService_Service service = new com.ihsganjlok.services.MenuManagementWebService_Service();
            com.ihsganjlok.services.MenuManagementWebService port = service.getMenuManagementWebServicePort();

            java.util.List<String> listMenu = port.getAllMenu();

            for (String baris : listMenu) {
                String[] kolom = baris.split("\\|");
                if (kolom.length >= 5) {
                    String id = kolom[0];
                    String nama = kolom[1];
                    String harga = kolom[2];
                    String kategori = kolom[4];
                    String status = (kolom.length > 5) ? kolom[5] : "Tersedia";

                    if (status.equalsIgnoreCase("Tersedia")) {
                        String formatItem = id + "-" + nama + "-" + harga;

                        if (kategori.equalsIgnoreCase("Makanan")) {
                            cmbMenuMakanan.addItem(formatItem);
                        } else if (kategori.equalsIgnoreCase("Minuman")) {
                            cmbMenuMinuman.addItem(formatItem);
                        }
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Gagal load menu dari database: " + e.getMessage());
        }
    }

    public FormReservasi(int userId, String nama, String hakAkses) {
        this.userId = userId;
        this.nama = nama;
        this.hakAkses = hakAkses;
        initComponents();
        
        ((javax.swing.table.DefaultTableModel)tabelReservasiMenu.getModel()).setRowCount(0);
        
        loadMenuToComboBox();

        try {
            clientSocket = new java.net.Socket("localhost", 6000);
            inFromServer = new java.io.BufferedReader(new java.io.InputStreamReader(clientSocket.getInputStream()));
            sendToServer = new java.io.DataOutputStream(clientSocket.getOutputStream());
            if (t == null) {
                t = new Thread(this, "Client Thread");
                t.start();
            }
        } catch (Exception ex) {
            System.out.println("Error di constructor = " + ex);
        }

        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu menu = new javax.swing.JMenu("Navigasi");
        javax.swing.JMenuItem itemKembali = new javax.swing.JMenuItem("Kembali ke Dashboard");
        itemKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    if (sendToServer != null) sendToServer.writeBytes("EXIT\n");
                    if (clientSocket != null) clientSocket.close();
                } catch (Exception ignored) {}
                new FormDashboard(FormReservasi.this.userId, FormReservasi.this.nama, FormReservasi.this.hakAkses).setVisible(true);
                FormReservasi.this.dispose();
            }
        });
        menu.add(itemKembali);
        menuBar.add(menu);
        this.setJMenuBar(menuBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbJam = new javax.swing.JComboBox<>();
        spnJumlahTamu = new javax.swing.JSpinner();
        spnTanggal = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelReservasiMenu = new javax.swing.JTable();
        btnKonfirmasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbMejaKosong = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        cmbMenuMinuman = new javax.swing.JComboBox<>();
        cmbMenuMakanan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelReservasiMeja = new javax.swing.JTable();
        qtyMakanan = new javax.swing.JSpinner();
        qtyMinuman = new javax.swing.JSpinner();
        btnEnterMakanan = new javax.swing.JButton();
        btnEnterMinuman = new javax.swing.JButton();
        btnDeleteMenu = new javax.swing.JButton();
        lblTotalHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00" }));
        cmbJam.setSelectedIndex(-1);

        spnTanggal.setModel(new javax.swing.SpinnerDateModel());

        tabelReservasiMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Menu", "Nama Menu", "Kategori", "Harga", "Quantity", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tabelReservasiMenu);

        btnKonfirmasi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnKonfirmasi.setText("Konfirmasi Booking");
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Reservation Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Silahkan pilih tanggal");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Silahkan pilih Jam");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Jumlah Tamu");

        cmbMejaKosong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbMejaKosong.setText("Cari meja kosong");
        cmbMejaKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMejaKosongActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        cmbMenuMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        cmbMenuMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Minuman");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Daftar Pesanan");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Makanan");

        tabelReservasiMeja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "No Meja", "Kapasitas", "Status"
            }
        ));
        jScrollPane3.setViewportView(tabelReservasiMeja);

        btnEnterMakanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnterMakanan.setText("Enter");
        btnEnterMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterMakananActionPerformed(evt);
            }
        });

        btnEnterMinuman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnterMinuman.setText("Enter");
        btnEnterMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterMinumanActionPerformed(evt);
            }
        });

        btnDeleteMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteMenu.setText("DELETE MENU");
        btnDeleteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMenuActionPerformed(evt);
            }
        });

        lblTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalHarga.setText("Total: Rp 0.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbJam, javax.swing.GroupLayout.Alignment.LEADING, 0, 162, Short.MAX_VALUE)
                                    .addComponent(spnTanggal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnJumlahTamu)))
                            .addComponent(cmbMejaKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(465, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKonfirmasi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7)
                                            .addComponent(cmbMenuMakanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(qtyMakanan)
                                            .addComponent(btnEnterMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5)
                                            .addComponent(cmbMenuMinuman, 0, 1, Short.MAX_VALUE)
                                            .addComponent(qtyMinuman)
                                            .addComponent(btnEnterMinuman, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(124, 124, 124)
                                        .addComponent(btnDeleteMenu))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(390, 390, 390)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbJam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnJumlahTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMejaKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMenuMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMenuMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtyMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnterMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnterMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteMenu)
                    .addComponent(lblTotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        try {
            int barisTerpilih = tabelReservasiMeja.getSelectedRow();
            if (barisTerpilih < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih salah satu meja kosong dari tabel terlebih dahulu!");
                return;
            }
            
            if (cmbJam.getSelectedIndex() == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih Jam Reservasi terlebih dahulu!");
                return;
            }
            
            String idMeja = tabelReservasiMeja.getValueAt(barisTerpilih, 0).toString();

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format((java.util.Date) spnTanggal.getValue());
        String jam = cmbJam.getSelectedItem().toString();
        String jumlahTamu = spnJumlahTamu.getValue().toString();
        String userID = String.valueOf(this.userId);

        StringBuilder cartPesanan = new StringBuilder();
        javax.swing.table.DefaultTableModel modelMenu = (javax.swing.table.DefaultTableModel) tabelReservasiMenu.getModel();

        for (int i = 0; i < modelMenu.getRowCount(); i++) {
            String idMenu = modelMenu.getValueAt(i, 0).toString();
            String qty = modelMenu.getValueAt(i, 4).toString();
            cartPesanan.append(idMenu).append(",").append(qty).append(";");
        }

        String stringPesanan = cartPesanan.toString();
        if (stringPesanan.isEmpty()) {
            stringPesanan = "0,0";
        }

        String pesan = "BOOKING_MEJA|" + userID + "|" + idMeja + "|" + tanggal + "|" + jam + "|" + jumlahTamu + "|" + stringPesanan;
        kirimKeServerTCP(pesan);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saat Konfirmasi Booking: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void cmbMejaKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMejaKosongActionPerformed
        try {
            if (cmbJam.getSelectedIndex() == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih Jam Reservasi terlebih dahulu!");
                return;
            }

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format((java.util.Date) spnTanggal.getValue());
            String jam = cmbJam.getSelectedItem().toString();
            String jumlahTamu = spnJumlahTamu.getValue().toString();
            
            if (Integer.parseInt(jumlahTamu) <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Jumlah tamu harus lebih dari 0!");
                return;
            }

            String pesan = "CARI_MEJA|" + tanggal + "|" + jam + "|" + jumlahTamu;

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelReservasiMeja.getModel();
            model.setRowCount(0);

            kirimKeServerTCP(pesan);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saat mencari meja: " + ex.getMessage());
        }
    }//GEN-LAST:event_cmbMejaKosongActionPerformed

    private void btnEnterMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterMakananActionPerformed

        String menu = cmbMenuMakanan.getSelectedItem().toString();
        int qty = (int) qtyMakanan.getValue();

        if (qty <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity harus lebih dari 0!");
            return;
        }

        String[] part = menu.split("-");
        String idMenu = part[0];
        String namaMenu = part[1];
        int harga = Integer.parseInt(part[2]);
        int subtotal = harga * qty;

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelReservasiMenu.getModel();
        model.addRow(new Object[]{idMenu, namaMenu, "Makanan", harga, qty, subtotal});

        hitungTotalHarga();
    }//GEN-LAST:event_btnEnterMakananActionPerformed

    private void btnEnterMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterMinumanActionPerformed

        String menu = cmbMenuMinuman.getSelectedItem().toString();
        int qty = (int) qtyMinuman.getValue();

        if (qty <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity harus lebih dari 0!");
            return;
        }

        String[] part = menu.split("-");
        String idMenu = part[0];
        String namaMenu = part[1];
        int harga = Integer.parseInt(part[2]);
        int subtotal = harga * qty;

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelReservasiMenu.getModel();
        model.addRow(new Object[]{idMenu, namaMenu, "Minuman", harga, qty, subtotal});

        hitungTotalHarga();
    }//GEN-LAST:event_btnEnterMinumanActionPerformed

    private void btnDeleteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMenuActionPerformed

        int barisTerpilih = tabelReservasiMenu.getSelectedRow();

        if (barisTerpilih == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih salah satu menu yang ingin dihapus dari daftar pesanan terlebih dahulu!");
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin membatalkan menu yang dipilih?",
                "Konfirmasi Hapus Item",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelReservasiMenu.getModel();
            model.removeRow(barisTerpilih);

            hitungTotalHarga();
        }
    }//GEN-LAST:event_btnDeleteMenuActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {
        new FormDashboard(this.userId, this.nama, this.hakAkses).setVisible(true);
        this.dispose();
    }

    public void kirimKeServerTCP(String pesan) {
        try {
            sendToServer.writeBytes(pesan + "\n");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal kirim: " + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReservasi(0, "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteMenu;
    private javax.swing.JButton btnEnterMakanan;
    private javax.swing.JButton btnEnterMinuman;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JComboBox<String> cmbJam;
    private javax.swing.JButton cmbMejaKosong;
    private javax.swing.JComboBox<String> cmbMenuMakanan;
    private javax.swing.JComboBox<String> cmbMenuMinuman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JSpinner qtyMakanan;
    private javax.swing.JSpinner qtyMinuman;
    private javax.swing.JSpinner spnJumlahTamu;
    private javax.swing.JSpinner spnTanggal;
    private javax.swing.JTable tabelReservasiMeja;
    private javax.swing.JTable tabelReservasiMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                String response = inFromServer.readLine();
                if (response == null) {
                    System.out.println("Koneksi ke TCP Server terputus.");
                    break;
                }
                
                if (response.trim().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Info Server: Tidak ada meja yang tersedia untuk jumlah tamu tersebut, atau terjadi error di Server.");
                    continue;
                }
                
                if (response.startsWith("ERROR|")) {
                    String[] msg = response.split("\\|");
                    javax.swing.JOptionPane.showMessageDialog(this, msg[1]);
                    continue;
                }
                
                if (response.startsWith("BOOKING_REPLY|")) {
                    String[] msg = response.split("\\|");
                    javax.swing.JOptionPane.showMessageDialog(this, "Notifikasi Server: " + msg[1]);
                } else {
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelReservasiMeja.getModel();
                    model.setRowCount(0);
                    String[] rows = response.split("#");
                    for (String row : rows) {
                        String[] kolom = row.split("\\|");
                        if (kolom.length == 4) {
                            model.addRow(new Object[]{kolom[0], kolom[1], kolom[2], kolom[3]});
                        }
                    }
                }
            } catch (Exception e) {
                System.out.println("Error di thread client: " + e.getMessage());
                break;
            }
        }
    }
}
