/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihsganjlokclienttcp;

/**
 *
 * @author LENOVO
 */
public class FormReservasi extends javax.swing.JFrame {

    private int userId;
    private String nama;
    private String hakAkses;

    public FormReservasi(int userId, String nama, String hakAkses) {
        this.userId = userId;
        this.nama = nama;
        this.hakAkses = hakAkses;
        initComponents();
        
        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu menu = new javax.swing.JMenu("Navigasi");
        javax.swing.JMenuItem itemKembali = new javax.swing.JMenuItem("Kembali ke Dashboard");
        itemKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new FormDashboard(FormReservasi.this.userId, FormReservasi.this.nama, FormReservasi.this.hakAkses).setVisible(true);
                FormReservasi.this.dispose();
            }
        });
        menu.add(itemKembali);
        menuBar.add(menu);
        this.setJMenuBar(menuBar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbJam = new javax.swing.JComboBox<>();
        spnJumlahTamu = new javax.swing.JSpinner();
        spnTanggal = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReservasi = new javax.swing.JTable();
        btnKonfirmasi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbMejaKosong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbJam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00" }));
        cmbJam.setSelectedIndex(-1);

        spnTanggal.setModel(new javax.swing.SpinnerDateModel());

        tableReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "No Meja", "Kapasitas", "Status"
            }
        ));
        jScrollPane2.setViewportView(tableReservasi);

        btnKonfirmasi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnKonfirmasi.setText("Konfirmasi Booking");
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Reservation Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Silahkan pilih tanggal");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Silahkan pilih Jam");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Jumlah Tamu");

        cmbMejaKosong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbMejaKosong.setText("Cari meja kosong");
        cmbMejaKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMejaKosongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMejaKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbJam, javax.swing.GroupLayout.Alignment.LEADING, 0, 162, Short.MAX_VALUE)
                                    .addComponent(spnTanggal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnJumlahTamu)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKonfirmasi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spnTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbJam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnJumlahTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMejaKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        // TODO add your handling code here:
        int barisTerpilih = tableReservasi.getSelectedRow();
        if (barisTerpilih < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih salah satu meja kosong dari tabel terlebih dahulu!");
            return;
        }

        // 1. Ambil data gabungan dari input & baris tabel yang diklik
        String idMeja = tableReservasi.getValueAt(barisTerpilih, 0).toString();
        String tanggal = spnTanggal.getValue().toString();
        String jam = cmbJam.getSelectedItem().toString();
        String jumlahTamu = spnJumlahTamu.getValue().toString();

        // Catatan: userID diambil dari parameter
        String userID = String.valueOf(this.userId);

        // 2. Format Pesan Rahasia TCP: BOOKING_MEJA|userID|idMeja|tanggal|jam|jumlahTamu
        String pesan = "BOOKING_MEJA|" + userID + "|" + idMeja + "|" + tanggal + "|" + jam + "|" + jumlahTamu;

        try {
            // 3. Kirim eksekusi ke Server
            java.util.List<String> balasan = kirimKeServerTCP(pesan);

            // Cek apakah pesan dari server menyatakan berhasil
            if (!balasan.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Notifikasi Server: " + balasan.get(0));

                // Refresh daftar meja agar meja yang barusan di-booking hilang dari tabel (opsional)
                cmbMejaKosongActionPerformed(null);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal melakukan booking: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void cmbMejaKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMejaKosongActionPerformed
        // TODO add your handling code here:
        String tanggal = spnTanggal.getValue().toString();
        String jam = cmbJam.getSelectedItem().toString();
        String jumlahTamu = spnJumlahTamu.getValue().toString();

        // 2. Format Pesan Rahasia TCP: CARI_MEJA|tanggal|jam|jumlahTamu
        String pesan = "CARI_MEJA|" + tanggal + "|" + jam + "|" + jumlahTamu;

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableReservasi.getModel();
        model.setRowCount(0); // Bersihkan tabel

        try {
            // 3. Kirim ke Server & Tangkap balasan
            java.util.List<String> balasan = kirimKeServerTCP(pesan);
            for (String data : balasan) {
                // Asumsi balasan dari Server: idMeja|nomorMeja|kapasitas|status
                String[] kolom = data.split("\\|");
                if (kolom.length == 4) {
                    model.addRow(new Object[]{kolom[0], kolom[1], kolom[2], kolom[3]});
                }
            }

            if (balasan.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Maaf, tidak ada meja kosong di waktu tersebut.");
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_cmbMejaKosongActionPerformed

    public java.util.List<String> kirimKeServerTCP(String pesan) {
        java.util.List<String> hasil = new java.util.ArrayList<String>();
        try {
            java.net.Socket socket = new java.net.Socket("localhost", 6000);
            java.io.PrintWriter out = new java.io.PrintWriter(socket.getOutputStream(), true);
            java.io.BufferedReader in = new java.io.BufferedReader(new java.io.InputStreamReader(socket.getInputStream()));
            out.println(pesan); // Kirim pesan custom
            String response = in.readLine(); // Tunggu jawaban

            if (response != null && !response.equals("")) {
                String[] rows = response.split("#");
                for (String row : rows) {
                    hasil.add(row);
                }
            }
            in.close();
            out.close();
            socket.close();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal koneksi ke TCP Server: " + ex.getMessage());
        }
        return hasil;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReservasi(0, "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JComboBox<String> cmbJam;
    private javax.swing.JButton cmbMejaKosong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spnJumlahTamu;
    private javax.swing.JSpinner spnTanggal;
    private javax.swing.JTable tableReservasi;
    // End of variables declaration//GEN-END:variables
}
